### PR TITLE
feat: add patch for software-properties-gtk

### PR DESCRIPTION
**Pull request by muggenhor**
This patch is taken against version 0.99.22.7 of that package.

This patch addresses the concerns raised in #5 by completely removing the "Ubuntu Pro" tab from the "Software & Updates" configuration manager.

### CODE REVIEW

**Comment by Skyedra** [comment]
Cool, thanks for this PR!

I will plan to merge once I have a chance to test locally and update instructions (or if you/someone wants to take the NOP strategy mentioned in the other PR, then I'm happy to go with that route instead, but it's not a blocker)

**Comment by muggenhor** [comment]
The update manager patch is relatively easy to replace with a NOP implementation. The software-properties-gtk package isn't as easy. The naive approach I just tried just fails at a different point for that.

**Comment by Skyedra** [comment]
Interesting, thanks for looking into this.

**Comment by Skyedra** [comment]
I am having a bit of difficulty applying the patch -- could be a 23.04 issue, or maybe I am just doing something wrong with my command syntax:

```
root@skye-VirtualBox:/# cd /
root@skye-VirtualBox:/# cat /home/skye/Downloads/software-properties-2204.patch | patch -p0 --dry-run
checking file /lib/python3/dist-packages/softwareproperties/gtk/SoftwarePropertiesGtk.py
Hunk #1 succeeded at 55 with fuzz 1 (offset 1 line).
Hunk #2 succeeded at 1665 (offset 8 lines).
checking file /usr/share/software-properties/gtkbuilder/main.ui
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored
```

For some reason, it thinks main.ui changes is already applied, even though if I check main.ui, it definitely still has the pro stuff in it:

```
root@skye-VirtualBox:/# grep 'This machine is not covered by an Ubuntu Pro subscription.' /usr/share/software-properties/gtkbuilder/main.ui
                                        <property name="label" translatable="yes">&lt;b&gt;This machine is not covered by an Ubuntu Pro subscription.&lt;/b&gt;
```

The patch, however, looks correct to me on visual inspection, so I'm a bit confused as to what's going on.

Any suggestions I might try?

**Comment by Skyedra** [comment]
It was indeed specific to 22.04, but does work on 22.04;  thanks for the patch!

**Pull request merged**
